#!/bin/bash
TUNNEL=$(ifconfig | grep -o "tun[0-9]")
if [[ -n $TUNNEL ]]; then
    echo "Found $TUNNEL"
    IP=`ifconfig "$TUNNEL" | grep -oE "([0-9]{1,3}\.){3}[0-9]{1,3}" | head -n 1`
    /usr/bin/deluge-console -c ~/.config/deluge "config --set listen_interface $IP"
else
    echo "No tunnels found"
fi
