#!/bin/sh
GAMEDIR="/home/oleerik/.PlayOnLinux//wineprefix/GuildWars2/drive_c/./Program Files/ArenaNet/Guild Wars 2"
RESOLUTION="1920x1080"
source "$PLAYONLINUX/lib/sources"

cd $GAMEDIR
# debug output really screws things with threaded optimisations, so turn them off 
export WINEPREFIX="/home/oleerik/.PlayOnLinux//wineprefix/GuildWars2"
export WINEDEBUG="-all"
export LD_PRELOAD="libpthread.so.0 libGL.so.1"

#POL_Log=Guild Wars 2
#ScriptID=Guild Wars 2

#export WINEARCH=wine64
# Note: Here (and in all other places where this flag is used), the word 
# "optimisations" can also be spelled "optimizations". The original spelling 
# of the word works for me, but the American spelling is what's in the 
# documentation for the drivers, and there have been reports that the original 
# spelling doesn't always work. 
export __GL_THREADED_OPTIMISATIONS=0 
export __GL_THREADED_OPTIMIZATIONS=0
#export __GL_SYNC_TO_VBLANK=1
export __GL_YIELD="NOTHING"
export CSMT=enabled
T1=$(date +%s)
#wine explorer /desktop=gw2,1920x1080 "Gw2.exe" -dx9single -maploadinfo
taskset -c 0-3 /opt/wine-staging/bin/wine explorer /desktop=gw2,$RESOLUTION "Gw2.exe" -dx9single -maploadinfo &
sleep 5
#taskset -cp 0-3 $(pidof Gw2.exe)
taskset -cp 7 $(pidof wineserver)
while kill -0 $(pidof Gw2.exe) >/dev/null 2>&1
do
    sleep 1
done
T2=$(date +%s)
diffsec="$(expr $T2 - $T1)"
echo | awk -v D=$diffsec '{printf "%02d:%02d:%02d\n",D/(60*60),D%(60*60)/60,D%60}' | while read OUTPUT; do notify-send "Guild Wars 2 Playtime:" "$OUTPUT"; done
echo | awk -v D=$diffsec '{printf "%02d:%02d:%02d\n",D/(60*60),D%(60*60)/60,D%60}'
